In [2]:
import numpy as np
import pandas as pd


In [4]:
dicts = {
    'text' : ['people watch campusx' , 'campusx watch campusx' , 'people write comment' , 'campusx write comment'],
    'output' :[1,1,0,0]
}

In [5]:
df = pd.DataFrame(dicts)

In [6]:
df.head()

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
cv = CountVectorizer()

In [38]:
bow = cv.fit_transform(df['text'])

In [39]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [40]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [41]:
bow[1].toarray()

array([[2, 0, 0, 1, 0]])

In [42]:
cv.transform(['campusx of watch hello campusx the comment ']).toarray()
# oov is handled they are not counted 
# we have to pass a list or a dataframe as document is needed to be passed

array([[2, 1, 0, 1, 0]])

 #### using n grams using hyperparameter in count vectoriser


In [32]:
cv = CountVectorizer(ngram_range = (1,3))

In [33]:
n_grams = cv.fit_transform(df['text'])

In [34]:
cv.vocabulary_

{'people': 6,
 'watch': 11,
 'campusx': 0,
 'people watch': 7,
 'watch campusx': 12,
 'people watch campusx': 8,
 'campusx watch': 1,
 'campusx watch campusx': 2,
 'write': 13,
 'comment': 5,
 'people write': 9,
 'write comment': 14,
 'people write comment': 10,
 'campusx write': 3,
 'campusx write comment': 4}

In [35]:
n_grams[0].toarray()

array([[1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0]])

In [36]:
n_grams[1].toarray()

array([[2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]])

#### usign Tf-Idf using TfidfVectorizer

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
tfidf = TfidfVectorizer()

In [46]:
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [49]:
tfidf.idf_

array([1.22314355, 1.51082562, 1.51082562, 1.51082562, 1.51082562])

In [51]:
tfidf.get_feature_names_out()

array(['campusx', 'comment', 'people', 'watch', 'write'], dtype=object)